name: tflite
description: A Flutter plugin for accessing TensorFlow Lite. Supports both iOS and Android.
version: 1.1.2
homepage: https://github.com/shaqian/flutter_tflite

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=3.4.1"

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: sq.flutter.tflite
        pluginClass: TflitePlugin
      ios:
        pluginClass: TflitePlugin


  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
